// packages/lit/src/date-picker.ts
/**
 * Lit DatePicker Component
 */

import { LitElement, html, css } from 'lit';
import { customElement, property, state, query } from 'lit/decorators.js';
import { DatePickerCore } from '@ldesign/datepicker-core';
import { formatDate } from '@ldesign/datepicker-shared';
import type { PickerType, PickerValue } from '@ldesign/datepicker-shared';

@customElement('ldate-picker')
export class LDatePicker extends LitElement {
  static styles = css`
    @import '@ldesign/datepicker-core/dist/style.css';

    :host {
      display: inline-block;
    }
  `;

  @property({ type: String })
  type: PickerType = 'date';

  @property({ type: String })
  format = 'YYYY-MM-DD';

  @property({ type: String })
  placeholder = '选择日期';

  @property({ type: String, attribute: 'start-placeholder' })
  startPlaceholder = '开始日期';

  @property({ type: String, attribute: 'end-placeholder' })
  endPlaceholder = '结束日期';

  @property({ type: String, attribute: 'range-separator' })
  rangeSeparator = '至';

  @property({ type: Boolean })
  clearable = true;

  @property({ type: Boolean })
  editable = true;

  @property({ type: Boolean })
  disabled = false;

  @property({ attribute: false })
  value: PickerValue = null;

  @state()
  private visible = false;

  @state()
  private core?: DatePickerCore;

  @query('.ldate-picker')
  private pickerEl?: HTMLElement;

  @query('.ldate-popper')
  private popperEl?: HTMLElement;

  connectedCallback() {
    super.connectedCallback();
    this.initCore();
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    this.core?.destroy();
  }

  private initCore() {
    this.core = new DatePickerCore({
      type: this.type,
      format: this.format,
      placeholder: this.placeholder,
      clearable: this.clearable,
      editable: this.editable,
      onChange: (value) => {
        this.value = value;
        this.dispatchEvent(new CustomEvent('change', { detail: value }));
      },
      onVisibleChange: (vis) => {
        this.visible = vis;
        this.dispatchEvent(new CustomEvent('visible-change', { detail: vis }));
      },
      onFocus: () => this.dispatchEvent(new Event('focus')),
      onBlur: () => this.dispatchEvent(new Event('blur')),
      onClear: () => this.dispatchEvent(new Event('clear')),
    });
  }

  private get isRange() {
    return this.type.endsWith('range');
  }

  private getDisplayValue(): string {
    if (!this.value) return '';
    if (this.value instanceof Date) {
      return formatDate(this.value, this.format);
    }
    return '';
  }

  private getDisplayStartValue(): string {
    if (!this.value || !Array.isArray(this.value)) return '';
    const [start] = this.value;
    return start ? formatDate(start, this.format) : '';
  }

  private getDisplayEndValue(): string {
    if (!this.value || !Array.isArray(this.value)) return '';
    const [, end] = this.value;
    return end ? formatDate(end, this.format) : '';
  }

  private handleInputClick() {
    if (!this.disabled) {
      this.core?.setVisible(!this.visible);
    }
  }

  private handleClear(e: Event) {
    e.stopPropagation();
    this.core?.clear();
  }

  private handleClickOutside = (e: MouseEvent) => {
    if (
      this.pickerEl &&
      this.popperEl &&
      !this.pickerEl.contains(e.target as Node) &&
      !this.popperEl.contains(e.target as Node)
    ) {
      this.core?.setVisible(false);
    }
  };

  updated(changedProperties: Map<string, any>) {
    if (changedProperties.has('visible')) {
      if (this.visible) {
        document.addEventListener('click', this.handleClickOutside);
      } else {
        document.removeEventListener('click', this.handleClickOutside);
      }
    }
  }

  render() {
    return html`
      <div class="ldate-picker">
        <div class="ldate-input" @click=${this.handleInputClick}>
          ${!this.isRange
            ? html`
                <input
                  class="ldate-input__inner"
                  .value=${this.getDisplayValue()}
                  placeholder=${this.placeholder}
                  ?disabled=${this.disabled}
                  ?readonly=${!this.editable}
                />
              `
            : html`
                <div class="ldate-range-input">
                  <input
                    class="ldate-range-input__inner"
                    .value=${this.getDisplayStartValue()}
                    placeholder=${this.startPlaceholder}
                    ?disabled=${this.disabled}
                    ?readonly=${!this.editable}
                  />
                  <span class="ldate-range-separator">${this.rangeSeparator}</span>
                  <input
                    class="ldate-range-input__inner"
                    .value=${this.getDisplayEndValue()}
                    placeholder=${this.endPlaceholder}
                    ?disabled=${this.disabled}
                    ?readonly=${!this.editable}
                  />
                </div>
              `}
          ${this.clearable && this.value && !this.disabled
            ? html`
                <span class="ldate-input__suffix" @click=${this.handleClear}>✕</span>
              `
            : ''}
        </div>

        ${this.visible
          ? html`
              <div class="ldate-popper ldate-zoom-enter">
                <!-- 面板内容将根据视图类型渲染 -->
                <div class="ldate-panel">DatePicker Panel (Lit)</div>
              </div>
            `
          : ''}
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ldate-picker': LDatePicker;
  }
}

// packages/react/src/components/DatePicker.tsx
/**
 * React DatePicker Component
 */

import React, { useRef, useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { useDatePicker } from '../hooks/useDatePicker';
import { formatDate } from '@ldesign/datepicker-shared';
import type { PickerType, PickerValue } from '@ldesign/datepicker-shared';
import { DatePanel } from './panels/DatePanel';
import { MonthPanel } from './panels/MonthPanel';
import { YearPanel } from './panels/YearPanel';
import { TimePanel } from './panels/TimePanel';
import '@ldesign/datepicker-core/dist/style.css';

export interface DatePickerProps {
  value?: PickerValue;
  type?: PickerType;
  format?: string;
  placeholder?: string;
  startPlaceholder?: string;
  endPlaceholder?: string;
  rangeSeparator?: string;
  clearable?: boolean;
  editable?: boolean;
  disabled?: boolean;
  onChange?: (value: PickerValue) => void;
  onFocus?: () => void;
  onBlur?: () => void;
  onClear?: () => void;
  onVisibleChange?: (visible: boolean) => void;
}

export const DatePicker: React.FC<DatePickerProps> = ({
  value,
  type = 'date',
  format,
  placeholder = '选择日期',
  startPlaceholder = '开始日期',
  endPlaceholder = '结束日期',
  rangeSeparator = '至',
  clearable = true,
  editable = true,
  disabled = false,
  onChange,
  onFocus,
  onBlur,
  onClear,
  onVisibleChange,
}) => {
  const pickerRef = useRef<HTMLDivElement>(null);
  const popperRef = useRef<HTMLDivElement>(null);
  const [popperStyle, setPopperStyle] = useState<React.CSSProperties>({});

  const {
    core,
    visible,
    state,
    config,
    selectDate,
    clear,
    setVisible,
    changeView,
    navigatePrev,
    navigateNext,
    setHoverDate,
  } = useDatePicker(
    {
      type,
      format,
      placeholder,
      clearable,
      editable,
      onChange,
      onFocus,
      onBlur,
      onClear,
      onVisibleChange,
    },
    onChange
  );

  const isRange = type.endsWith('range');

  // 格式化显示值
  const getDisplayValue = (): string => {
    if (!value) return '';
    if (value instanceof Date) {
      return formatDate(value, format || 'YYYY-MM-DD');
    }
    return '';
  };

  const getDisplayStartValue = (): string => {
    if (!value || !Array.isArray(value)) return '';
    const [start] = value;
    return start ? formatDate(start, format || 'YYYY-MM-DD') : '';
  };

  const getDisplayEndValue = (): string => {
    if (!value || !Array.isArray(value)) return '';
    const [, end] = value;
    return end ? formatDate(end, format || 'YYYY-MM-DD') : '';
  };

  // 更新弹出层位置
  useEffect(() => {
    if (visible && pickerRef.current) {
      const rect = pickerRef.current.getBoundingClientRect();
      setPopperStyle({
        position: 'fixed',
        top: `${rect.bottom + 4}px`,
        left: `${rect.left}px`,
        minWidth: `${rect.width}px`,
      });
    }
  }, [visible]);

  // 监听外部点击
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (
        pickerRef.current &&
        popperRef.current &&
        !pickerRef.current.contains(e.target as Node) &&
        !popperRef.current.contains(e.target as Node)
      ) {
        setVisible(false);
      }
    };

    if (visible) {
      document.addEventListener('click', handleClickOutside);
      return () => document.removeEventListener('click', handleClickOutside);
    }
  }, [visible, setVisible]);

  // 事件处理
  const handleInputClick = () => {
    if (!disabled) {
      setVisible(!visible);
    }
  };

  const handleClear = (e: React.MouseEvent) => {
    e.stopPropagation();
    clear();
  };

  const handleSelectDate = (date: Date) => {
    selectDate(date);
  };

  const handleSelectMonth = (month: number) => {
    if (state) {
      const newDate = new Date(state.currentDate.getFullYear(), month, 1);
      selectDate(newDate);
    }
  };

  const handleSelectYear = (year: number) => {
    if (state) {
      const newDate = new Date(year, state.currentDate.getMonth(), 1);
      selectDate(newDate);
    }
  };

  const handleSelectTime = (time: Date) => {
    selectDate(time);
  };

  return (
    <div className="ldate-picker" ref={pickerRef}>
      {/* 输入框 */}
      <div className="ldate-input" onClick={handleInputClick}>
        {!isRange ? (
          <input
            className="ldate-input__inner"
            value={getDisplayValue()}
            placeholder={placeholder}
            disabled={disabled}
            readOnly={!editable}
            onFocus={onFocus}
            onBlur={onBlur}
          />
        ) : (
          <div className="ldate-range-input">
            <input
              className="ldate-range-input__inner"
              value={getDisplayStartValue()}
              placeholder={startPlaceholder}
              disabled={disabled}
              readOnly={!editable}
              onFocus={onFocus}
            />
            <span className="ldate-range-separator">{rangeSeparator}</span>
            <input
              className="ldate-range-input__inner"
              value={getDisplayEndValue()}
              placeholder={endPlaceholder}
              disabled={disabled}
              readOnly={!editable}
              onFocus={onFocus}
            />
          </div>
        )}

        {/* 清除按钮 */}
        {clearable && value && !disabled && (
          <span className="ldate-input__suffix" onClick={handleClear}>
            ✕
          </span>
        )}
      </div>

      {/* 下拉面板 */}
      {visible &&
        createPortal(
          <div className="ldate-popper ldate-zoom-enter" style={popperStyle} ref={popperRef}>
            {state?.view === 'date' && (
              <DatePanel
                core={core}
                state={state}
                config={config}
                onSelectDate={handleSelectDate}
              />
            )}

            {state?.view === 'month' && (
              <MonthPanel
                core={core}
                state={state}
                config={config}
                onSelectMonth={handleSelectMonth}
              />
            )}

            {state?.view === 'year' && (
              <YearPanel
                core={core}
                state={state}
                config={config}
                onSelectYear={handleSelectYear}
              />
            )}

            {state?.view === 'time' && (
              <TimePanel
                core={core}
                state={state}
                config={config}
                onSelectTime={handleSelectTime}
              />
            )}
          </div>,
          document.body
        )}
    </div>
  );
};
