// packages/vue/src/components/panels/YearPanel.vue
<template>
  <div class="ldate-panel ldate-year-panel">
    <!-- 头部 -->
    <div class="ldate-panel__header">
      <span class="ldate-panel__arrow" @click="handlePrevDecade">«</span>
      <span class="ldate-panel__header-label">
        {{ headerLabel }}
      </span>
      <span class="ldate-panel__arrow" @click="handleNextDecade">»</span>
    </div>
    
    <!-- 年份网格 -->
    <div class="ldate-year-panel__body">
      <div
        v-for="(row, rowIndex) in cells"
        :key="rowIndex"
        class="ldate-year-panel__row"
      >
        <div
          v-for="(cell, cellIndex) in row"
          :key="cellIndex"
          :class="getCellClass(cell)"
          @click="handleCellClick(cell)"
        >
          {{ cell.text }}
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { YearPanel as YearPanelCore } from '@ldesign/datepicker-core';
import type { YearCell } from '@ldesign/datepicker-shared';

const props = defineProps<{
  core: any;
  state: any;
  config: any;
}>();

const emit = defineEmits<{
  'select-year': [year: number];
}>();

// Computed
const headerLabel = computed(() => {
  if (!props.state) return '';
  
  const panel = new YearPanelCore({
    year: props.state.currentDate.getFullYear(),
    value: null,
  });
  
  const [start, end] = panel.getYearRange();
  return `${start} - ${end}`;
});

const cells = computed(() => {
  if (!props.state) return [];
  
  const date = props.state.currentDate;
  const value = props.state.value instanceof Date ? props.state.value : null;
  
  const panel = new YearPanelCore({
    year: date.getFullYear(),
    value,
    disabledDate: props.config?.disabledDate,
  });
  
  return panel.generateCells();
});

// Methods
const getCellClass = (cell: YearCell) => {
  return [
    'ldate-cell',
    'ldate-year-cell',
    {
      'ldate-cell--selected': cell.selected,
      'ldate-cell--disabled': cell.disabled,
      'ldate-cell--in-range': cell.inRange,
      'ldate-cell--range-start': cell.rangeStart,
      'ldate-cell--range-end': cell.rangeEnd,
    },
  ];
};

const handleCellClick = (cell: YearCell) => {
  if (!cell.disabled) {
    emit('select-year', cell.year);
  }
};

const handlePrevDecade = () => {
  props.core?.navigatePrev();
};

const handleNextDecade = () => {
  props.core?.navigateNext();
};
</script>

// packages/react/src/components/panels/YearPanel.tsx
/**
 * React YearPanel Component
 */

import React, { useMemo } from 'react';
import { YearPanel as YearPanelCore } from '@ldesign/datepicker-core';
import type { YearCell } from '@ldesign/datepicker-shared';

interface YearPanelProps {
  core: any;
  state: any;
  config: any;
  onSelectYear: (year: number) => void;
}

export const YearPanel: React.FC<YearPanelProps> = ({ core, state, config, onSelectYear }) => {
  const headerLabel = useMemo(() => {
    if (!state) return '';

    const panel = new YearPanelCore({
      year: state.currentDate.getFullYear(),
      value: null,
    });

    const [start, end] = panel.getYearRange();
    return `${start} - ${end}`;
  }, [state]);

  const cells = useMemo(() => {
    if (!state) return [];

    const date = state.currentDate;
    const value = state.value instanceof Date ? state.value : null;

    const panel = new YearPanelCore({
      year: date.getFullYear(),
      value,
      disabledDate: config?.disabledDate,
    });

    return panel.generateCells();
  }, [state, config]);

  const getCellClass = (cell: YearCell): string => {
    const classes = ['ldate-cell', 'ldate-year-cell'];
    if (cell.selected) classes.push('ldate-cell--selected');
    if (cell.disabled) classes.push('ldate-cell--disabled');
    if (cell.inRange) classes.push('ldate-cell--in-range');
    if (cell.rangeStart) classes.push('ldate-cell--range-start');
    if (cell.rangeEnd) classes.push('ldate-cell--range-end');
    return classes.join(' ');
  };

  const handleCellClick = (cell: YearCell) => {
    if (!cell.disabled) {
      onSelectYear(cell.year);
    }
  };

  const handlePrevDecade = () => {
    core?.navigatePrev();
  };

  const handleNextDecade = () => {
    core?.navigateNext();
  };

  return (
    <div className="ldate-panel ldate-year-panel">
      {/* 头部 */}
      <div className="ldate-panel__header">
        <span className="ldate-panel__arrow" onClick={handlePrevDecade}>
          «
        </span>
        <span className="ldate-panel__header-label">{headerLabel}</span>
        <span className="ldate-panel__arrow" onClick={handleNextDecade}>
          »
        </span>
      </div>

      {/* 年份网格 */}
      <div className="ldate-year-panel__body">
        {cells.map((row, rowIndex) => (
          <div key={rowIndex} className="ldate-year-panel__row">
            {row.map((cell, cellIndex) => (
              <div
                key={cellIndex}
                className={getCellClass(cell)}
                onClick={() => handleCellClick(cell)}
              >
                {cell.text}
              </div>
            ))}
          </div>
        ))}
      </div>
    </div>
  );
};
